server:
  port: 80
spring:
  application:
    name: spring-security-auth-server
  datasource:
    url: jdbc:mysql://192.168.88.128:3306/harry?useUnicode=true&serverTimezone=CTT&characterEncoding=utf8&allowMultiQueries=true
    username: harry
    password: abcd1234
  security:
    user:
      name: admin
      password: 12345
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: harry-client-id
          client-secret: harry-client-secret
  redis:
    host: 192.168.88.128
    port: 6379
mybatis:
  mapper-locations: classpath:/META-INF/mappings/*.xml
  config-location: classpath:/META-INF/mybatis-config.xml

harry:
  security:
    social:
      open: true
      qq:
        app-id: 101575121
        app-secret: a98ba0e8b2f4e5ef53484a9e0e474360
      weixin:
        app-id: wx7fdc8fedf501f527
        app-secret: 17d1054662a2f839c6acf6148bb5047e